version: 2
jobs:
  build:
    working_directory: ~/repo/impl
    docker:
      - image: circleci/node:10.16.0
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 5777 -p 7545
    steps:
      - checkout:
          path: "~/repo"
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install npm wee
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Migrate Contracts
          command: npx truffle migrate --network=development --contracts_build_directory="$PWD/build/dev/contracts"
      - run:
          name: Tests Contracts
          command: npx truffle test --network=development test/**/*.js

